import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Event from '#models/event'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    await Event.createMany([
      {
        title: 'Jazz Under the Stars: Summer Edition',
        subtitle: 'A Night of Smooth Jazz and Cool Breezes',
        description:
          'Join us for an unforgettable evening of smooth jazz under the summer stars. Enjoy performances by top jazz musicians and immerse yourself in a night of captivating melodies and relaxing vibes.',
        facebookLink: 'https://www.facebook.com/jazzunderthestars',
        instagramLink: 'https://www.instagram.com/jazzunderthestars',
        websiteLink: 'https://www.jazzunderthestars.com',
        youtubeLink: 'https://www.youtube.com/jazzunderthestars',
        eventStart: '2024-07-10T19:00:00',
        eventEnd: '2024-07-10T22:00:00',
        locationId: 5,
        vendorId: 3,
      },
      {
        title: 'Summer Beach Festival 2024',
        subtitle: 'Fun in the Sun with Music, Food, and Games',
        description:
          'Experience the ultimate summer beach festival with live music, delicious food, exciting games, and more. Bring your friends and family for a day of fun and sun!',
        facebookLink: 'https://www.facebook.com/summerbeachfestival',
        instagramLink: 'https://www.instagram.com/summerbeachfestival',
        websiteLink: 'https://www.summerbeachfestival.com',
        youtubeLink: 'https://www.youtube.com/summerbeachfestival',
        eventStart: '2024-07-15T10:00:00',
        eventEnd: '2024-07-15T15:00:00',
        locationId: 12,
        vendorId: 3,
      },
      {
        title: 'Rock Legends Live',
        subtitle: 'A Tribute to the Greatest Rock Bands',
        description:
          'Get ready to rock out with tributes to the greatest rock bands of all time. This high-energy concert will feature some of the best rock hits from the 70s, 80s, and 90s.',
        facebookLink: 'https://www.facebook.com/rocklegendslive',
        instagramLink: 'https://www.instagram.com/rocklegendslive',
        websiteLink: 'https://www.rocklegendslive.com',
        youtubeLink: 'https://www.youtube.com/rocklegendslive',
        eventStart: '2024-08-05T18:00:00',
        eventEnd: '2024-08-05T21:00:00',
        locationId: 8,
        vendorId: 3,
      },
      {
        title: 'Comedy Night at The Laugh Lounge',
        subtitle: 'An Evening of Laughter and Fun',
        description:
          'Join us for a night of non-stop laughter with some of the funniest comedians in the business. The Laugh Lounge is the perfect place to unwind and enjoy a great comedy show.',
        facebookLink: 'https://www.facebook.com/laughlounge',
        instagramLink: 'https://www.instagram.com/laughlounge',
        websiteLink: 'https://www.laughlounge.com',
        youtubeLink: 'https://www.youtube.com/laughlounge',
        eventStart: '2024-07-25T20:00:00',
        eventEnd: '2024-07-25T23:00:00',
        locationId: 3,
        vendorId: 3,
      },
      {
        title: 'Art in the Park: Summer Exhibit',
        subtitle: "A Display of Local Artists' Works",
        description:
          'Stroll through the park and enjoy a stunning exhibit of artworks by local artists. From paintings to sculptures, this outdoor event is a celebration of creativity and talent.',
        facebookLink: 'https://www.facebook.com/artinthepark',
        instagramLink: 'https://www.instagram.com/artinthepark',
        websiteLink: 'https://www.artinthepark.com',
        youtubeLink: 'https://www.youtube.com/artinthepark',
        eventStart: '2024-06-30T14:00:00',
        eventEnd: '2024-06-30T18:00:00',
        locationId: 7,
        vendorId: 3,
      },
      {
        title: 'Classical Evenings at the Symphony',
        subtitle: 'An Evening of Timeless Classical Music',
        description:
          "Enjoy an enchanting evening of classical music performed by the city's top symphony orchestra. This event promises to be a feast for the ears and a tranquil escape from the everyday hustle and bustle.",
        facebookLink: 'https://www.facebook.com/classicalevenings',
        instagramLink: 'https://www.instagram.com/classicalevenings',
        websiteLink: 'https://www.classicalevenings.com',
        youtubeLink: 'https://www.youtube.com/classicalevenings',
        eventStart: '2024-07-20T19:00:00',
        eventEnd: '2024-07-20T21:30:00',
        locationId: 15,
        vendorId: 3,
      },
      {
        title: 'Food Truck Fiesta',
        subtitle: 'A Culinary Adventure with Gourmet Food Trucks',
        description:
          "Satisfy your taste buds at the Food Truck Fiesta, where a variety of gourmet food trucks will be serving up delicious dishes from around the world. It's a culinary adventure you won't want to miss!",
        facebookLink: 'https://www.facebook.com/foodtruckfiesta',
        instagramLink: 'https://www.instagram.com/foodtruckfiesta',
        websiteLink: 'https://www.foodtruckfiesta.com',
        youtubeLink: 'https://www.youtube.com/foodtruckfiesta',
        eventStart: '2024-08-15T11:00:00',
        eventEnd: '2024-08-15T14:00:00',
        locationId: 10,
        vendorId: 3,
      },
      {
        title: 'Outdoor Movie Night: Classic Films',
        subtitle: 'Watch Classic Movies Under the Stars',
        description:
          'Bring your blanket and enjoy a night under the stars watching classic movies on the big screen. This outdoor movie night is perfect for film enthusiasts and families alike.',
        facebookLink: 'https://www.facebook.com/outdoormovienight',
        instagramLink: 'https://www.instagram.com/outdoormovienight',
        websiteLink: 'https://www.outdoormovienight.com',
        youtubeLink: 'https://www.youtube.com/outdoormovienight',
        eventStart: '2024-07-05T20:00:00',
        eventEnd: '2024-07-05T23:00:00',
        locationId: 6,
        vendorId: 3,
      },
      {
        title: 'Country Music Fest',
        subtitle: 'A Celebration of Country Music',
        description:
          'Join us for the Country Music Fest, featuring live performances by top country music artists. Enjoy a day of great music, food, and fun activities for all ages.',
        facebookLink: 'https://www.facebook.com/countrymusicfest',
        instagramLink: 'https://www.instagram.com/countrymusicfest',
        websiteLink: 'https://www.countrymusicfest.com',
        youtubeLink: 'https://www.youtube.com/countrymusicfest',
        eventStart: '2024-08-01T12:00:00',
        eventEnd: '2024-08-01T17:00:00',
        locationId: 1,
        vendorId: 3,
      },
      {
        title: 'Wine and Cheese Tasting',
        subtitle: 'An Evening of Fine Wines and Gourmet Cheeses',
        description:
          'Indulge in an evening of fine wines and gourmet cheeses at our Wine and Cheese Tasting event. Learn about the art of pairing and enjoy a variety of exquisite flavors.',
        facebookLink: 'https://www.facebook.com/wineandcheesetasting',
        instagramLink: 'https://www.instagram.com/wineandcheesetasting',
        websiteLink: 'https://www.wineandcheesetasting.com',
        youtubeLink: 'https://www.youtube.com/wineandcheesetasting',
        eventStart: '2024-07-22T18:00:00',
        eventEnd: '2024-07-22T21:00:00',
        locationId: 2,
        vendorId: 3,
      },
      {
        title: 'Reggae Summer Jam',
        subtitle: 'Feel the Rhythm of Reggae',
        description:
          'Come and experience the vibrant rhythms of reggae music at the Reggae Summer Jam. Enjoy live performances by talented reggae bands and dance the night away.',
        facebookLink: 'https://www.facebook.com/reggaesummerjam',
        instagramLink: 'https://www.instagram.com/reggaesummerjam',
        websiteLink: 'https://www.reggaesummerjam.com',
        youtubeLink: 'https://www.youtube.com/reggaesummerjam',
        eventStart: '2024-07-28T16:00:00',
        eventEnd: '2024-07-28T20:00:00',
        locationId: 3,
        vendorId: 3,
      },
      {
        title: 'Latin Dance Fiesta',
        subtitle: 'An Evening of Passionate Latin Dance',
        description:
          'Get ready to move your feet at the Latin Dance Fiesta. Experience the energy and passion of Latin dance with live music and dance performances that will keep you dancing all night long.',
        facebookLink: 'https://www.facebook.com/latindancefiesta',
        instagramLink: 'https://www.instagram.com/latindancefiesta',
        websiteLink: 'https://www.latindancefiesta.com',
        youtubeLink: 'https://www.youtube.com/latindancefiesta',
        eventStart: '2024-08-12T18:00:00',
        eventEnd: '2024-08-12T22:00:00',
        locationId: 4,
        vendorId: 3,
      },
      {
        title: 'The Great BBQ Cook-Off',
        subtitle: 'A Competition for the Best BBQ in Town',
        description:
          'Do you have what it takes to be the BBQ champion? Join us for The Great BBQ Cook-Off and showcase your grilling skills. Taste delicious BBQ from various competitors and vote for your favorite.',
        facebookLink: 'https://www.facebook.com/bbqcookoff',
        instagramLink: 'https://www.instagram.com/bbqcookoff',
        websiteLink: 'https://www.bbqcookoff.com',
        youtubeLink: 'https://www.youtube.com/bbqcookoff',
        eventStart: '2024-07-18T11:00:00',
        eventEnd: '2024-07-18T14:00:00',
        locationId: 5,
        vendorId: 3,
      },
      {
        title: 'Hip Hop Dance Battle',
        subtitle: 'The Ultimate Dance Showdown',
        description:
          "Witness the ultimate dance showdown at the Hip Hop Dance Battle. Dancers from all over will compete in a high-energy battle to see who has the best moves. Don't miss this electrifying event!",
        facebookLink: 'https://www.facebook.com/hiphopdancebattle',
        instagramLink: 'https://www.instagram.com/hiphopdancebattle',
        websiteLink: 'https://www.hiphopdancebattle.com',
        youtubeLink: 'https://www.youtube.com/hiphopdancebattle',
        eventStart: '2024-08-03T17:00:00',
        eventEnd: '2024-08-03T21:00:00',
        locationId: 6,
        vendorId: 3,
      },
      {
        title: 'Outdoor Yoga Retreat',
        subtitle: 'A Day of Relaxation and Mindfulness',
        description:
          "Find your inner peace at our Outdoor Yoga Retreat. Spend a day practicing yoga in a serene outdoor setting, led by experienced instructors. It's the perfect way to relax and rejuvenate.",
        facebookLink: 'https://www.facebook.com/outdooryogaretreat',
        instagramLink: 'https://www.instagram.com/outdooryogaretreat',
        websiteLink: 'https://www.outdooryogaretreat.com',
        youtubeLink: 'https://www.youtube.com/outdooryogaretreat',
        eventStart: '2024-06-25T09:00:00',
        eventEnd: '2024-06-25T12:00:00',
        locationId: 7,
        vendorId: 3,
      },
      {
        title: 'Indie Film Festival',
        subtitle: 'Showcasing the Best Independent Films',
        description:
          'Celebrate the art of independent filmmaking at the Indie Film Festival. Watch a diverse selection of films from emerging filmmakers and enjoy Q&A sessions with directors and actors.',
        facebookLink: 'https://www.facebook.com/indiefilmfestival',
        instagramLink: 'https://www.instagram.com/indiefilmfestival',
        websiteLink: 'https://www.indiefilmfestival.com',
        youtubeLink: 'https://www.youtube.com/indiefilmfestival',
        eventStart: '2024-08-08T15:00:00',
        eventEnd: '2024-08-08T19:00:00',
        locationId: 8,
        vendorId: 3,
      },
      {
        title: 'Tech Innovators Conference',
        subtitle: 'Exploring the Future of Technology',
        description:
          'Join industry leaders and innovators at the Tech Innovators Conference to explore the latest trends and advancements in technology. Network with professionals and learn from expert speakers.',
        facebookLink: 'https://www.facebook.com/techinnovators',
        instagramLink: 'https://www.instagram.com/techinnovators',
        websiteLink: 'https://www.techinnovators.com',
        youtubeLink: 'https://www.youtube.com/techinnovators',
        eventStart: '2024-07-12T09:00:00',
        eventEnd: '2024-07-12T14:00:00',
        locationId: 9,
        vendorId: 3,
      },
      {
        title: 'Family Fun Day',
        subtitle: 'A Day of Fun Activities for the Whole Family',
        description:
          "Bring the whole family for a day of fun activities at Family Fun Day. Enjoy games, live entertainment, food stalls, and more. There's something for everyone to enjoy!",
        facebookLink: 'https://www.facebook.com/familyfunday',
        instagramLink: 'https://www.instagram.com/familyfunday',
        websiteLink: 'https://www.familyfunday.com',
        youtubeLink: 'https://www.youtube.com/familyfunday',
        eventStart: '2024-06-28T10:00:00',
        eventEnd: '2024-06-28T14:00:00',
        locationId: 10,
        vendorId: 3,
      },
      {
        title: 'Outdoor Adventure Expo',
        subtitle: 'Explore the Great Outdoors',
        description:
          'Discover the latest gear and trends in outdoor adventure at the Outdoor Adventure Expo. Meet experts, attend workshops, and get inspired for your next outdoor adventure.',
        facebookLink: 'https://www.facebook.com/outdoorexpo',
        instagramLink: 'https://www.instagram.com/outdoorexpo',
        websiteLink: 'https://www.outdoorexpo.com',
        youtubeLink: 'https://www.youtube.com/outdoorexpo',
        eventStart: '2024-07-30T11:00:00',
        eventEnd: '2024-07-30T15:00:00',
        locationId: 12,
        vendorId: 3,
      },
      {
        title: 'Science Fiction Convention',
        subtitle: 'Celebrating Sci-Fi Culture and Creativity',
        description:
          "Join fellow sci-fi enthusiasts at the Science Fiction Convention. Enjoy panel discussions, cosplay contests, and meet your favorite sci-fi authors and actors. It's a celebration of all things sci-fi!",
        facebookLink: 'https://www.facebook.com/scificonvention',
        instagramLink: 'https://www.instagram.com/scificonvention',
        websiteLink: 'https://www.scificonvention.com',
        youtubeLink: 'https://www.youtube.com/scificonvention',
        eventStart: '2024-08-18T10:00:00',
        eventEnd: '2024-08-18T14:00:00',
        locationId: 13,
        vendorId: 3,
      },
      {
        title: 'Culinary Arts Workshop',
        subtitle: 'A Hands-On Cooking Experience',
        description:
          'Learn from top chefs at our Culinary Arts Workshop. This hands-on cooking experience will teach you new techniques and recipes that you can recreate at home. Perfect for food lovers and aspiring chefs.',
        facebookLink: 'https://www.facebook.com/culinaryworkshop',
        instagramLink: 'https://www.instagram.com/culinaryworkshop',
        websiteLink: 'https://www.culinaryworkshop.com',
        youtubeLink: 'https://www.youtube.com/culinaryworkshop',
        eventStart: '2024-07-17T14:00:00',
        eventEnd: '2024-07-17T17:00:00',
        locationId: 15,
        vendorId: 3,
      },
      {
        title: 'Mindfulness Meditation Retreat',
        subtitle: 'A Journey to Inner Peace and Calm',
        description:
          'Embark on a journey to inner peace at our Mindfulness Meditation Retreat. Learn meditation techniques, practice mindfulness, and find a sense of calm and relaxation.',
        facebookLink: 'https://www.facebook.com/meditationretreat',
        instagramLink: 'https://www.instagram.com/meditationretreat',
        websiteLink: 'https://www.meditationretreat.com',
        youtubeLink: 'https://www.youtube.com/meditationretreat',
        eventStart: '2024-06-24T09:00:00',
        eventEnd: '2024-06-24T12:00:00',
        locationId: 12,
        vendorId: 3,
      },
      {
        title: 'Summer Jazz Festival',
        subtitle: 'A Celebration of Jazz Music Under the Stars',
        description:
          'Join us for an unforgettable night of jazz music featuring talented musicians from around the world. Enjoy smooth melodies and soulful rhythms in a magical outdoor setting.',
        facebookLink: 'https://www.facebook.com/summerjazzfestival',
        instagramLink: 'https://www.instagram.com/summerjazzfestival',
        websiteLink: 'https://www.summerjazzfestival.com',
        youtubeLink: 'https://www.youtube.com/summerjazzfestival',
        eventStart: '2024-06-25T19:00:00',
        eventEnd: '2024-06-25T23:00:00',
        locationId: 3,
      },
      {
        title: 'Food Truck Fiesta',
        subtitle: 'A Culinary Adventure for Food Lovers',
        description:
          'Experience the ultimate food truck extravaganza with a diverse array of gourmet dishes from around the world. Treat your taste buds to a night of delicious food and vibrant atmosphere.',
        facebookLink: 'https://www.facebook.com/foodtruckfiesta',
        instagramLink: 'https://www.instagram.com/foodtruckfiesta',
        websiteLink: 'https://www.foodtruckfiesta.com',
        youtubeLink: 'https://www.youtube.com/foodtruckfiesta',
        eventStart: '2024-07-10T17:00:00',
        eventEnd: '2024-07-10T21:00:00',
        locationId: 8,
      },
      {
        title: 'Art in the Park',
        subtitle: 'Celebrating Creativity and Community',
        description:
          'Join us for an inspiring day of art and culture in the heart of the city park. Explore a diverse range of artworks, interact with artists, and enjoy live performances throughout the day.',
        facebookLink: 'https://www.facebook.com/artinthepark',
        instagramLink: 'https://www.instagram.com/artinthepark',
        websiteLink: 'https://www.artinthepark.com',
        youtubeLink: 'https://www.youtube.com/artinthepark',
        eventStart: '2024-07-15T10:00:00',
        eventEnd: '2024-07-15T15:00:00',
        locationId: 5,
      },
      {
        title: 'Rock the Block Party',
        subtitle: 'An Epic Street Festival of Music and Fun',
        description:
          "Get ready to rock out at the biggest block party of the summer! Enjoy live bands, DJ sets, food trucks, and interactive activities for all ages. Don't miss this high-energy celebration!",
        facebookLink: 'https://www.facebook.com/rocktheblockparty',
        instagramLink: 'https://www.instagram.com/rocktheblockparty',
        websiteLink: 'https://www.rocktheblockparty.com',
        youtubeLink: 'https://www.youtube.com/rocktheblockparty',
        eventStart: '2024-07-28T18:00:00',
        eventEnd: '2024-07-28T22:00:00',
        locationId: 12,
      },
      {
        title: 'Cultural Fusion',
        subtitle: 'Exploring Diversity Through Music and Dance',
        description:
          'Celebrate cultural diversity with a dynamic showcase of music, dance, and traditions from around the world. Immerse yourself in a colorful tapestry of performances that will captivate and inspire.',
        facebookLink: 'https://www.facebook.com/culturalfusion',
        instagramLink: 'https://www.instagram.com/culturalfusion',
        websiteLink: 'https://www.culturalfusion.com',
        youtubeLink: 'https://www.youtube.com/culturalfusion',
        eventStart: '2024-08-05T16:30:00',
        eventEnd: '2024-08-05T20:30:00',
        locationId: 9,
      },
      {
        title: "Midsummer Night's Dream",
        subtitle: 'An Enchanted Evening of Shakespearean Theatre',
        description:
          "Step into the magical world of Shakespeare's 'A Midsummer Night's Dream' performed under the stars. Experience romance, comedy, and enchantment in a captivating outdoor setting.",
        facebookLink: 'https://www.facebook.com/midsummernightsdream',
        instagramLink: 'https://www.instagram.com/midsummernightsdream',
        websiteLink: 'https://www.midsummernightsdream.com',
        youtubeLink: 'https://www.youtube.com/midsummernightsdream',
        eventStart: '2024-08-10T19:30:00',
        eventEnd: '2024-08-10T22:30:00',
        locationId: 6,
        vendorId: 3,
      },
      {
        title: 'Summer Salsa Night',
        subtitle: 'Dance the Night Away with Hot Latin Beats',
        description:
          'Heat up the dance floor with sizzling salsa rhythms and Latin beats! Join us for a night of lively music, dance lessons, and performances by top salsa artists. No partner necessary!',
        facebookLink: 'https://www.facebook.com/summersalsanight',
        instagramLink: 'https://www.instagram.com/summersalsanight',
        websiteLink: 'https://www.summersalsanight.com',
        youtubeLink: 'https://www.youtube.com/summersalsanight',
        eventStart: '2024-08-15T20:00:00',
        eventEnd: '2024-08-15T23:00:00',
        locationId: 10,
        vendorId: 3,
      },
      {
        title: 'Festival of Lights',
        subtitle: 'A Spectacular Celebration of Cultural Diversity',
        description:
          'Experience a mesmerizing display of lights, performances, and cultural showcases from around the world. Celebrate unity and diversity under the night sky with family-friendly activities.',
        facebookLink: 'https://www.facebook.com/festivaloflights',
        instagramLink: 'https://www.instagram.com/festivaloflights',
        websiteLink: 'https://www.festivaloflights.com',
        youtubeLink: 'https://www.youtube.com/festivaloflights',
        eventStart: '2024-08-20T19:00:00',
        eventEnd: '2024-08-20T23:00:00',
        locationId: 2,
        vendorId: 3,
      },
      {
        title: 'Summer Comedy Showcase',
        subtitle: 'Laughs Galore with Top Stand-Up Comedians',
        description:
          'Get ready to bust a gut with hilarious stand-up comedy from some of the best comedians in the business. A night of non-stop laughter and unforgettable moments awaits!',
        facebookLink: 'https://www.facebook.com/summercomedyshowcase',
        instagramLink: 'https://www.instagram.com/summercomedyshowcase',
        websiteLink: 'https://www.summercomedyshowcase.com',
        youtubeLink: 'https://www.youtube.com/summercomedyshowcase',
        eventStart: '2024-08-25T19:30:00',
        eventEnd: '2024-08-25T22:30:00',
        locationId: 4,
        vendorId: 3,
      },
      {
        title: 'Carnival Extravaganza',
        subtitle: 'A Festive Celebration of Music, Dance, and Fun',
        description:
          'Step right up to the carnival extravaganza of the summer! Enjoy thrilling rides, delicious treats, live music, and dazzling performances that will delight visitors of all ages.',
        facebookLink: 'https://www.facebook.com/carnivalextravaganza',
        instagramLink: 'https://www.instagram.com/carnivalextravaganza',
        websiteLink: 'https://www.carnivalextravaganza.com',
        youtubeLink: 'https://www.youtube.com/carnivalextravaganza',
        eventStart: '2024-06-28T16:00:00',
        eventEnd: '2024-06-28T21:00:00',
        locationId: 7,
        vendorId: 3,
      },
      {
        title: 'Garden Serenade',
        subtitle: 'An Evening of Classical Music in a Botanical Paradise',
        description:
          'Immerse yourself in the beauty of classical music surrounded by blooming gardens. Enjoy enchanting melodies performed by talented musicians in a serene and picturesque setting.',
        facebookLink: 'https://www.facebook.com/gardenserenade',
        instagramLink: 'https://www.instagram.com/gardenserenade',
        websiteLink: 'https://www.gardenserenade.com',
        youtubeLink: 'https://www.youtube.com/gardenserenade',
        eventStart: '2024-07-05T18:30:00',
        eventEnd: '2024-07-05T21:30:00',
        locationId: 11,
        vendorId: 3,
      },
      {
        title: 'Summer Movie Marathon',
        subtitle: 'Outdoor Cinema Bliss Under the Stars',
        description:
          'Grab your blankets and popcorn for a cinematic journey under the stars. Experience classic films and family favorites in an enchanting outdoor setting.',
        facebookLink: 'https://www.facebook.com/summermoviemarathon',
        instagramLink: 'https://www.instagram.com/summermoviemarathon',
        websiteLink: 'https://www.summermoviemarathon.com',
        youtubeLink: 'https://www.youtube.com/summermoviemarathon',
        eventStart: '2024-07-20T20:00:00',
        eventEnd: '2024-07-20T23:00:00',
        locationId: 13,
        vendorId: 3,
      },
      {
        title: 'Sunset Yoga Retreat',
        subtitle: 'Relax and Rejuvenate with Sunset Yoga',
        description:
          'Unwind with a soothing yoga session as the sun sets over the tranquil beach. Connect with your inner peace and recharge your mind, body, and spirit in a serene natural environment.',
        facebookLink: 'https://www.facebook.com/sunsetyogaretreat',
        instagramLink: 'https://www.instagram.com/sunsetyogaretreat',
        websiteLink: 'https://www.sunsetyogaretreat.com',
        youtubeLink: 'https://www.youtube.com/sunsetyogaretreat',
        eventStart: '2024-07-12T18:00:00',
        eventEnd: '2024-07-12T20:00:00',
        locationId: 14,
        vendorId: 3,
      },
      {
        title: 'Summer Fashion Showcase',
        subtitle: 'Glamour, Style, and Runway Excellence',
        description:
          'Experience the latest trends and designs at our summer fashion showcase. From haute couture to casual chic, this event celebrates creativity and style in the world of fashion.',
        facebookLink: 'https://www.facebook.com/summerfashionshowcase',
        instagramLink: 'https://www.instagram.com/summerfashionshowcase',
        websiteLink: 'https://www.summerfashionshowcase.com',
        youtubeLink: 'https://www.youtube.com/summerfashionshowcase',
        eventStart: '2024-07-18T19:30:00',
        eventEnd: '2024-07-18T22:30:00',
        locationId: 15,
        vendorId: 3,
      },
      {
        title: 'Summer Wine Tasting',
        subtitle: 'Sip, Swirl, and Savor Delicious Wines',
        description:
          'Indulge in an evening of wine tasting featuring a selection of fine wines from around the world. Discover new favorites and enjoy gourmet pairings in a relaxed and sophisticated atmosphere.',
        facebookLink: 'https://www.facebook.com/summerwinetasting',
        instagramLink: 'https://www.instagram.com/summerwinetasting',
        websiteLink: 'https://www.summerwinetasting.com',
        youtubeLink: 'https://www.youtube.com/summerwinetasting',
        eventStart: '2024-08-03T18:00:00',
        eventEnd: '2024-08-03T21:00:00',
        locationId: 1,
        vendorId: 3,
      },
      {
        title: 'Summer Drum Circle',
        subtitle: 'Join the Rhythm of the Summer Beat',
        description:
          'Feel the pulse of the season with a vibrant drum circle under the open sky. Bring your drums or just your hands and join the community in a rhythmic celebration of summer.',
        facebookLink: 'https://www.facebook.com/summerdrumcircle',
        instagramLink: 'https://www.instagram.com/summerdrumcircle',
        websiteLink: 'https://www.summerdrumcircle.com',
        youtubeLink: 'https://www.youtube.com/summerdrumcircle',
        eventStart: '2024-07-08T17:00:00',
        eventEnd: '2024-07-08T19:00:00',
        locationId: 3,
        vendorId: 3,
      },
      {
        title: 'Summer Science Fair',
        subtitle: 'Inspiring Curiosity and Innovation',
        description:
          'Explore the wonders of science with interactive exhibits, experiments, and demonstrations for all ages. Join us for a day of discovery and hands-on learning in a fun and educational environment.',
        facebookLink: 'https://www.facebook.com/summersciencefair',
        instagramLink: 'https://www.instagram.com/summersciencefair',
        websiteLink: 'https://www.summersciencefair.com',
        youtubeLink: 'https://www.youtube.com/summersciencefair',
        eventStart: '2024-07-25T10:00:00',
        eventEnd: '2024-07-25T15:00:00',
        locationId: 9,
        vendorId: 3,
      },
      {
        title: 'Summer Shakespeare in the Park',
        subtitle: 'Classic Theatre Al Fresco',
        description:
          'Experience the magic of Shakespeare performed in the beauty of nature. Enjoy timeless tales, captivating performances, and the enchantment of live theatre under the summer sky.',
        facebookLink: 'https://www.facebook.com/summershakespeare',
        instagramLink: 'https://www.instagram.com/summershakespeare',
        websiteLink: 'https://www.summershakespeare.com',
        youtubeLink: 'https://www.youtube.com/summershakespeare',
        eventStart: '2024-08-01T19:00:00',
        eventEnd: '2024-08-01T22:00:00',
        locationId: 11,
        vendorId: 3,
      },
      {
        title: 'Summer Dance Party',
        subtitle: 'Groove to the Hottest Beats of the Season',
        description:
          'Get ready to dance the night away with an electrifying lineup of DJs and performers. This summer dance party promises non-stop energy, incredible music, and unforgettable moments.',
        facebookLink: 'https://www.facebook.com/summerdanceparty',
        instagramLink: 'https://www.instagram.com/summerdanceparty',
        websiteLink: 'https://www.summerdanceparty.com',
        youtubeLink: 'https://www.youtube.com/summerdanceparty',
        eventStart: '2024-08-08T21:00:00',
        eventEnd: '2024-08-08T23:59:00',
        locationId: 5,
        vendorId: 3,
      },
    ])
  }
}
