import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Event from '#models/event'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    await Event.createMany([
      {
        title: 'Concert Nine Inch Nails',
        subtitle: 'Premier concert de la tournée',
        description: 'Premier concert de la tournée',
        facebookLink: 'https://www.facebook.com/',
        instagramLink: 'https://www.instagram.com/',
        websiteLink: 'https://www.website.com/',
        youtubeLink: 'https://www.youtube.com/',
        eventStart: DateTime.fromISO('06/20/2024, 12:12 PM'),
        eventEnd: DateTime.fromISO('06/20/2024, 14:12 PM'),
        locationId: 20
      },
      {
        title: 'Concert Nine Inch Nails',
        subtitle: 'Premier concert de la tournée',
        description: 'Premier concert de la tournée',
        facebookLink: 'https://www.facebook.com/',
        instagramLink: 'https://www.instagram.com/',
        websiteLink: 'https://www.website.com/',
        youtubeLink: 'https://www.youtube.com/',
        eventStart: DateTime.fromISO('06/20/2024, 12:12 PM'),
        eventEnd: DateTime.fromISO('06/20/2024, 14:12 PM'),
        locationId: 20
      },
      {
        title: 'Rock Festival',
        subtitle: 'Opening Night',
        description: 'Join us for an amazing night of rock music',
        facebookLink: 'https://www.facebook.com/rockfestival',
        instagramLink: 'https://www.instagram.com/rockfestival',
        websiteLink: 'https://www.rockfestival.com',
        youtubeLink: 'https://www.youtube.com/rockfestival',
        eventStart: DateTime.fromISO('07/01/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('07/01/2024, 08:00 PM'),
        locationId: 22
      },
      {
        title: 'Jazz Night',
        subtitle: 'Smooth Jazz Evening',
        description: 'Enjoy a night of smooth jazz',
        facebookLink: 'https://www.facebook.com/jazznight',
        instagramLink: 'https://www.instagram.com/jazznight',
        websiteLink: 'https://www.jazznight.com',
        youtubeLink: 'https://www.youtube.com/jazznight',
        eventStart: DateTime.fromISO('07/05/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('07/05/2024, 09:00 PM'),
        locationId: 16
      },
      {
        title: 'Classical Concert',
        subtitle: 'Beethoven Symphony',
        description: 'Experience the beauty of Beethoven\'s symphony',
        facebookLink: 'https://www.facebook.com/classicalconcert',
        instagramLink: 'https://www.instagram.com/classicalconcert',
        websiteLink: 'https://www.classicalconcert.com',
        youtubeLink: 'https://www.youtube.com/classicalconcert',
        eventStart: DateTime.fromISO('07/10/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('07/10/2024, 10:00 PM'),
        locationId: 18
      },
      {
        title: 'Pop Star Live',
        subtitle: 'World Tour',
        description: 'Don\'t miss the pop sensation live',
        facebookLink: 'https://www.facebook.com/popstarlive',
        instagramLink: 'https://www.instagram.com/popstarlive',
        websiteLink: 'https://www.popstarlive.com',
        youtubeLink: 'https://www.youtube.com/popstarlive',
        eventStart: DateTime.fromISO('07/15/2024, 07:30 PM'),
        eventEnd: DateTime.fromISO('07/15/2024, 09:30 PM'),
        locationId: 24
      },
      {
        title: 'Indie Band Night',
        subtitle: 'Indie Music Extravaganza',
        description: 'A night of the best indie music',
        facebookLink: 'https://www.facebook.com/indiebandnight',
        instagramLink: 'https://www.instagram.com/indiebandnight',
        websiteLink: 'https://www.indiebandnight.com',
        youtubeLink: 'https://www.youtube.com/indiebandnight',
        eventStart: DateTime.fromISO('07/20/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('07/20/2024, 08:00 PM'),
        locationId: 17
      },
      {
        title: 'Blues Festival',
        subtitle: 'Blues Night Out',
        description: 'Feel the blues with top artists',
        facebookLink: 'https://www.facebook.com/bluesfestival',
        instagramLink: 'https://www.instagram.com/bluesfestival',
        websiteLink: 'https://www.bluesfestival.com',
        youtubeLink: 'https://www.youtube.com/bluesfestival',
        eventStart: DateTime.fromISO('07/25/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('07/25/2024, 09:00 PM'),
        locationId: 19
      },
      {
        title: 'Country Music Fest',
        subtitle: 'Country Hits',
        description: 'The best country music in one night',
        facebookLink: 'https://www.facebook.com/countrymusicfest',
        instagramLink: 'https://www.instagram.com/countrymusicfest',
        websiteLink: 'https://www.countrymusicfest.com',
        youtubeLink: 'https://www.youtube.com/countrymusicfest',
        eventStart: DateTime.fromISO('07/30/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('07/30/2024, 10:00 PM'),
        locationId: 21
      },
      {
        title: 'Hip Hop Showdown',
        subtitle: 'Rap Battles',
        description: 'Top rappers face off in epic battles',
        facebookLink: 'https://www.facebook.com/hiphopshowdown',
        instagramLink: 'https://www.instagram.com/hiphopshowdown',
        websiteLink: 'https://www.hiphopshowdown.com',
        youtubeLink: 'https://www.youtube.com/hiphopshowdown',
        eventStart: DateTime.fromISO('08/05/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('08/05/2024, 09:00 PM'),
        locationId: 15
      },
      {
        title: 'EDM Night',
        subtitle: 'Electronic Beats',
        description: 'Dance all night to the best EDM tracks',
        facebookLink: 'https://www.facebook.com/edmnight',
        instagramLink: 'https://www.instagram.com/edmnight',
        websiteLink: 'https://www.edmnight.com',
        youtubeLink: 'https://www.youtube.com/edmnight',
        eventStart: DateTime.fromISO('08/10/2024, 09:00 PM'),
        eventEnd: DateTime.fromISO('08/10/2024, 11:00 PM'),
        locationId: 23
      },
      {
        title: 'Folk Music Evening',
        subtitle: 'Traditional Tunes',
        description: 'A night of heartwarming folk music',
        facebookLink: 'https://www.facebook.com/folkmusicevening',
        instagramLink: 'https://www.instagram.com/folkmusicevening',
        websiteLink: 'https://www.folkmusicevening.com',
        youtubeLink: 'https://www.youtube.com/folkmusicevening',
        eventStart: DateTime.fromISO('08/15/2024, 06:30 PM'),
        eventEnd: DateTime.fromISO('08/15/2024, 08:30 PM'),
        locationId: 25
      },
      {
        title: 'Latin Fiesta',
        subtitle: 'Salsa Night',
        description: 'Get ready to salsa all night long',
        facebookLink: 'https://www.facebook.com/latinfiesta',
        instagramLink: 'https://www.instagram.com/latinfiesta',
        websiteLink: 'https://www.latinfiesta.com',
        youtubeLink: 'https://www.youtube.com/latinfiesta',
        eventStart: DateTime.fromISO('08/20/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('08/20/2024, 10:00 PM'),
        locationId: 16
      },
      {
        title: 'Reggae Jam',
        subtitle: 'Feel the Vibes',
        description: 'Chill out with the best reggae tunes',
        facebookLink: 'https://www.facebook.com/reggaejam',
        instagramLink: 'https://www.instagram.com/reggaejam',
        websiteLink: 'https://www.reggaejam.com',
        youtubeLink: 'https://www.youtube.com/reggaejam',
        eventStart: DateTime.fromISO('08/25/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('08/25/2024, 09:00 PM'),
        locationId: 18
      },
      {
        title: 'Opera Night',
        subtitle: 'The Magic Flute',
        description: 'An enchanting evening of opera',
        facebookLink: 'https://www.facebook.com/operanight',
        instagramLink: 'https://www.instagram.com/operanight',
        websiteLink: 'https://www.operanight.com',
        youtubeLink: 'https://www.youtube.com/operanight',
        eventStart: DateTime.fromISO('09/01/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('09/01/2024, 10:00 PM'),
        locationId: 19
      },
      {
        title: 'Metal Madness',
        subtitle: 'Heavy Metal Night',
        description: 'Experience the power of heavy metal',
        facebookLink: 'https://www.facebook.com/metalmadness',
        instagramLink: 'https://www.instagram.com/metalmadness',
        websiteLink: 'https://www.metalmadness.com',
        youtubeLink: 'https://www.youtube.com/metalmadness',
        eventStart: DateTime.fromISO('09/05/2024, 09:00 PM'),
        eventEnd: DateTime.fromISO('09/05/2024, 11:00 PM'),
        locationId: 17
      },
      {
        title: 'Punk Rock Night',
        subtitle: 'Punk Extravaganza',
        description: 'A night of raw punk rock energy',
        facebookLink: 'https://www.facebook.com/punkrocknight',
        instagramLink: 'https://www.instagram.com/punkrocknight',
        websiteLink: 'https://www.punkrocknight.com',
        youtubeLink: 'https://www.youtube.com/punkrocknight',
        eventStart: DateTime.fromISO('09/10/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('09/10/2024, 09:00 PM'),
        locationId: 24
      },
      {
        title: 'Soulful Sunday',
        subtitle: 'Soul Music Night',
        description: 'Relax with the best soul music',
        facebookLink: 'https://www.facebook.com/soulfulsunday',
        instagramLink: 'https://www.instagram.com/soulfulsunday',
        websiteLink: 'https://www.soulfulsunday.com',
        youtubeLink: 'https://www.youtube.com/soulfulsunday',
        eventStart: DateTime.fromISO('09/15/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('09/15/2024, 08:00 PM'),
        locationId: 21
      },
      {
        title: 'Alternative Nights',
        subtitle: 'Alt Rock Party',
        description: 'Rock out with the best alternative bands',
        facebookLink: 'https://www.facebook.com/alternativenights',
        instagramLink: 'https://www.instagram.com/alternativenights',
        websiteLink: 'https://www.alternativenights.com',
        youtubeLink: 'https://www.youtube.com/alternativenights',
        eventStart: DateTime.fromISO('09/20/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('09/20/2024, 10:00 PM'),
        locationId: 23
      },
      {
        title: 'Symphony Under the Stars',
        subtitle: 'Outdoor Classical Concert',
        description: 'Enjoy classical music under the stars',
        facebookLink: 'https://www.facebook.com/symphonyunderthestars',
        instagramLink: 'https://www.instagram.com/symphonyunderthestars',
        websiteLink: 'https://www.symphonyunderthestars.com',
        youtubeLink: 'https://www.youtube.com/symphonyunderthestars',
        eventStart: DateTime.fromISO('09/25/2024, 07:30 PM'),
        eventEnd: DateTime.fromISO('09/25/2024, 09:30 PM'),
        locationId: 22
      },
      {
        title: 'World Music Festival',
        subtitle: 'Global Beats',
        description: 'Experience music from around the world',
        facebookLink: 'https://www.facebook.com/worldmusicfestival',
        instagramLink: 'https://www.instagram.com/worldmusicfestival',
        websiteLink: 'https://www.worldmusicfestival.com',
        youtubeLink: 'https://www.youtube.com/worldmusicfestival',
        eventStart: DateTime.fromISO('09/30/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('09/30/2024, 08:00 PM'),
        locationId: 20
      },
      {
        title: 'Synthwave Night',
        subtitle: 'Retro Future',
        description: 'A night of retro synthwave music',
        facebookLink: 'https://www.facebook.com/synthwavenight',
        instagramLink: 'https://www.instagram.com/synthwavenight',
        websiteLink: 'https://www.synthwavenight.com',
        youtubeLink: 'https://www.youtube.com/synthwavenight',
        eventStart: DateTime.fromISO('10/05/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('10/05/2024, 10:00 PM'),
        locationId: 15
      },
      {
        title: 'Acoustic Evening',
        subtitle: 'Unplugged',
        description: 'An intimate night of acoustic music',
        facebookLink: 'https://www.facebook.com/acousticevening',
        instagramLink: 'https://www.instagram.com/acousticevening',
        websiteLink: 'https://www.acousticevening.com',
        youtubeLink: 'https://www.youtube.com/acousticevening',
        eventStart: DateTime.fromISO('10/10/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('10/10/2024, 09:00 PM'),
        locationId: 25
      },
      {
        title: 'Gospel Gathering',
        subtitle: 'Soulful Praise',
        description: 'A powerful night of gospel music',
        facebookLink: 'https://www.facebook.com/gospelgathering',
        instagramLink: 'https://www.instagram.com/gospelgathering',
        websiteLink: 'https://www.gospelgathering.com',
        youtubeLink: 'https://www.youtube.com/gospelgathering',
        eventStart: DateTime.fromISO('10/15/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('10/15/2024, 08:00 PM'),
        locationId: 24
      },
      {
        title: 'RnB Nights',
        subtitle: 'Smooth RnB Hits',
        description: 'An evening of smooth RnB hits',
        facebookLink: 'https://www.facebook.com/rnbnights',
        instagramLink: 'https://www.instagram.com/rnbnights',
        websiteLink: 'https://www.rnbnights.com',
        youtubeLink: 'https://www.youtube.com/rnbnights',
        eventStart: DateTime.fromISO('10/20/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('10/20/2024, 10:00 PM'),
        locationId: 18
      },
      {
        title: 'Electronic Fusion',
        subtitle: 'EDM Extravaganza',
        description: 'The best electronic music in one night',
        facebookLink: 'https://www.facebook.com/electronicfusion',
        instagramLink: 'https://www.instagram.com/electronicfusion',
        websiteLink: 'https://www.electronicfusion.com',
        youtubeLink: 'https://www.youtube.com/electronicfusion',
        eventStart: DateTime.fromISO('10/25/2024, 09:00 PM'),
        eventEnd: DateTime.fromISO('10/25/2024, 11:00 PM'),
        locationId: 21
      },
      {
        title: 'Rock Legends',
        subtitle: 'Tribute Night',
        description: 'Tribute to the greatest rock legends',
        facebookLink: 'https://www.facebook.com/rocklegends',
        instagramLink: 'https://www.instagram.com/rocklegends',
        websiteLink: 'https://www.rocklegends.com',
        youtubeLink: 'https://www.youtube.com/rocklegends',
        eventStart: DateTime.fromISO('10/30/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('10/30/2024, 10:00 PM'),
        locationId: 20
      },
      {
        title: 'New Wave Night',
        subtitle: '80s Revival',
        description: 'Reviving the best of 80s new wave',
        facebookLink: 'https://www.facebook.com/newwavenight',
        instagramLink: 'https://www.instagram.com/newwavenight',
        websiteLink: 'https://www.newwavenight.com',
        youtubeLink: 'https://www.youtube.com/newwavenight',
        eventStart: DateTime.fromISO('11/05/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('11/05/2024, 10:00 PM'),
        locationId: 19
      },
      {
        title: 'Live DJ Set',
        subtitle: 'Night of Beats',
        description: 'A night with the best live DJ sets',
        facebookLink: 'https://www.facebook.com/livedjset',
        instagramLink: 'https://www.instagram.com/livedjset',
        websiteLink: 'https://www.livedjset.com',
        youtubeLink: 'https://www.youtube.com/livedjset',
        eventStart: DateTime.fromISO('11/10/2024, 09:00 PM'),
        eventEnd: DateTime.fromISO('11/10/2024, 11:00 PM'),
        locationId: 22
      },
      {
        title: 'Techno Night',
        subtitle: 'Techno Beats',
        description: 'Experience the best techno music',
        facebookLink: 'https://www.facebook.com/technonight',
        instagramLink: 'https://www.instagram.com/technonight',
        websiteLink: 'https://www.technonight.com',
        youtubeLink: 'https://www.youtube.com/technonight',
        eventStart: DateTime.fromISO('11/15/2024, 09:00 PM'),
        eventEnd: DateTime.fromISO('11/15/2024, 11:00 PM'),
        locationId: 17
      },
      {
        title: 'Funk Fiesta',
        subtitle: 'Groovy Night',
        description: 'Get your groove on with the best funk music',
        facebookLink: 'https://www.facebook.com/funkfiesta',
        instagramLink: 'https://www.instagram.com/funkfiesta',
        websiteLink: 'https://www.funkfiesta.com',
        youtubeLink: 'https://www.youtube.com/funkfiesta',
        eventStart: DateTime.fromISO('11/20/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('11/20/2024, 09:00 PM'),
        locationId: 23
      },
      {
        title: 'Classical Evening',
        subtitle: 'Mozart\'s Masterpieces',
        description: 'A night of Mozart\'s greatest works',
        facebookLink: 'https://www.facebook.com/classicalevening',
        instagramLink: 'https://www.instagram.com/classicalevening',
        websiteLink: 'https://www.classicalevening.com',
        youtubeLink: 'https://www.youtube.com/classicalevening',
        eventStart: DateTime.fromISO('11/25/2024, 07:30 PM'),
        eventEnd: DateTime.fromISO('11/25/2024, 09:30 PM'),
        locationId: 16
      },
      {
        title: 'Alternative Soundscapes',
        subtitle: 'Indie and Alternative',
        description: 'Dive into the world of indie and alternative music',
        facebookLink: 'https://www.facebook.com/alternativesoundscapes',
        instagramLink: 'https://www.instagram.com/alternativesoundscapes',
        websiteLink: 'https://www.alternativesoundscapes.com',
        youtubeLink: 'https://www.youtube.com/alternativesoundscapes',
        eventStart: DateTime.fromISO('12/01/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('12/01/2024, 10:00 PM'),
        locationId: 25
      },
      {
        title: 'Hip Hop Night',
        subtitle: 'Rap and RnB',
        description: 'A night dedicated to the best rap and RnB',
        facebookLink: 'https://www.facebook.com/hiphopnight',
        instagramLink: 'https://www.instagram.com/hiphopnight',
        websiteLink: 'https://www.hiphopnight.com',
        youtubeLink: 'https://www.youtube.com/hiphopnight',
        eventStart: DateTime.fromISO('12/05/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('12/05/2024, 09:00 PM'),
        locationId: 19
      },
      {
        title: 'Latin Rhythms',
        subtitle: 'Salsa and More',
        description: 'Dance the night away to the best Latin rhythms',
        facebookLink: 'https://www.facebook.com/latinrhythms',
        instagramLink: 'https://www.instagram.com/latinrhythms',
        websiteLink: 'https://www.latinrhythms.com',
        youtubeLink: 'https://www.youtube.com/latinrhythms',
        eventStart: DateTime.fromISO('12/10/2024, 08:00 PM'),
        eventEnd: DateTime.fromISO('12/10/2024, 10:00 PM'),
        locationId: 15
      },
      {
        title: 'Jazz Fusion',
        subtitle: 'Modern Jazz',
        description: 'An evening of modern jazz fusion',
        facebookLink: 'https://www.facebook.com/jazzfusion',
        instagramLink: 'https://www.instagram.com/jazzfusion',
        websiteLink: 'https://www.jazzfusion.com',
        youtubeLink: 'https://www.youtube.com/jazzfusion',
        eventStart: DateTime.fromISO('12/15/2024, 07:00 PM'),
        eventEnd: DateTime.fromISO('12/15/2024, 09:00 PM'),
        locationId: 18
      },
      {
        title: 'Christmas Concert',
        subtitle: 'Holiday Classics',
        description: 'Celebrate the season with holiday classics',
        facebookLink: 'https://www.facebook.com/christmasconcert',
        instagramLink: 'https://www.instagram.com/christmasconcert',
        websiteLink: 'https://www.christmasconcert.com',
        youtubeLink: 'https://www.youtube.com/christmasconcert',
        eventStart: DateTime.fromISO('12/20/2024, 06:00 PM'),
        eventEnd: DateTime.fromISO('12/20/2024, 08:00 PM'),
        locationId: 21
      },
      {
        title: 'New Year\'s Eve Bash',
        subtitle: 'Ring in the New Year',
        description: 'Celebrate the New Year with a bang',
        facebookLink: 'https://www.facebook.com/newyearsevebash',
        instagramLink: 'https://www.instagram.com/newyearsevebash',
        websiteLink: 'https://www.newyearsevebash.com',
        youtubeLink: 'https://www.youtube.com/newyearsevebash',
        eventStart: DateTime.fromISO('12/31/2024, 10:00 PM'),
        eventEnd: DateTime.fromISO('01/01/2025, 12:00 AM'),
        locationId: 22
      },
      {
        title: 'Indie Pop Night',
        subtitle: 'Catchy Tunes',
        description: 'A night of catchy indie pop tunes',
        facebookLink: 'https://www.facebook.com/indiepopnight',
        instagramLink: 'https://www.instagram.com/indiepopnight',
        websiteLink: 'https://www.indiepopnight.com',
        youtubeLink: 'https://www.youtube.com/indiepopnight',
        eventStart: DateTime.fromISO('01/05/2025, 07:00 PM'),
        eventEnd: DateTime.fromISO('01/05/2025, 09:00 PM'),
        locationId: 23
      },
      {
        title: 'Acoustic Sessions',
        subtitle: 'Unplugged and Intimate',
        description: 'Intimate acoustic performances',
        facebookLink: 'https://www.facebook.com/acousticsessions',
        instagramLink: 'https://www.instagram.com/acousticsessions',
        websiteLink: 'https://www.acousticsessions.com',
        youtubeLink: 'https://www.youtube.com/acousticsessions',
        eventStart: DateTime.fromISO('01/10/2025, 06:00 PM'),
        eventEnd: DateTime.fromISO('01/10/2025, 08:00 PM'),
        locationId: 24
      },
      {
        title: 'Folk Revival',
        subtitle: 'Traditional Folk',
        description: 'Reviving traditional folk music',
        facebookLink: 'https://www.facebook.com/folkrevival',
        instagramLink: 'https://www.instagram.com/folkrevival',
        websiteLink: 'https://www.folkrevival.com',
        youtubeLink: 'https://www.youtube.com/folkrevival',
        eventStart: DateTime.fromISO('01/15/2025, 07:00 PM'),
        eventEnd: DateTime.fromISO('01/15/2025, 09:00 PM'),
        locationId: 16
      },
      {
        title: 'Piano Recital',
        subtitle: 'Classical Piano',
        description: 'An evening of classical piano music',
        facebookLink: 'https://www.facebook.com/pianorecital',
        instagramLink: 'https://www.instagram.com/pianorecital',
        websiteLink: 'https://www.pianorecital.com',
        youtubeLink: 'https://www.youtube.com/pianorecital',
        eventStart: DateTime.fromISO('01/20/2025, 08:00 PM'),
        eventEnd: DateTime.fromISO('01/20/2025, 10:00 PM'),
        locationId: 25
      },
      {
        title: 'World Beats',
        subtitle: 'Global Music',
        description: 'A celebration of global music',
        facebookLink: 'https://www.facebook.com/worldbeats',
        instagramLink: 'https://www.instagram.com/worldbeats',
        websiteLink: 'https://www.worldbeats.com',
        youtubeLink: 'https://www.youtube.com/worldbeats',
        eventStart: DateTime.fromISO('01/25/2025, 06:00 PM'),
        eventEnd: DateTime.fromISO('01/25/2025, 08:00 PM'),
        locationId: 19
      },
      {
        title: 'Chamber Music',
        subtitle: 'Intimate Classical',
        description: 'An intimate evening of chamber music',
        facebookLink: 'https://www.facebook.com/chambermusic',
        instagramLink: 'https://www.instagram.com/chambermusic',
        websiteLink: 'https://www.chambermusic.com',
        youtubeLink: 'https://www.youtube.com/chambermusic',
        eventStart: DateTime.fromISO('01/30/2025, 07:30 PM'),
        eventEnd: DateTime.fromISO('01/30/2025, 09:30 PM'),
        locationId: 20
      },
      {
        title: 'Blues Night',
        subtitle: 'Blues and Brews',
        description: 'A night of soulful blues music',
        facebookLink: 'https://www.facebook.com/bluesnight',
        instagramLink: 'https://www.instagram.com/bluesnight',
        websiteLink: 'https://www.bluesnight.com',
        youtubeLink: 'https://www.youtube.com/bluesnight',
        eventStart: DateTime.fromISO('02/05/2025, 07:00 PM'),
        eventEnd: DateTime.fromISO('02/05/2025, 09:00 PM'),
        locationId: 18
      },
      {
        title: 'Reggae Vibes',
        subtitle: 'One Love',
        description: 'Feel the rhythm with the best reggae music',
        facebookLink: 'https://www.facebook.com/reggaevibes',
        instagramLink: 'https://www.instagram.com/reggaevibes',
        websiteLink: 'https://www.reggaevibes.com',
        youtubeLink: 'https://www.youtube.com/reggaevibes',
        eventStart: DateTime.fromISO('02/10/2025, 08:00 PM'),
        eventEnd: DateTime.fromISO('02/10/2025, 10:00 PM'),
        locationId: 15
      },
      {
        title: 'Rock Revolution',
        subtitle: 'Modern Rock',
        description: 'The best of modern rock',
        facebookLink: 'https://www.facebook.com/rockrevolution',
        instagramLink: 'https://www.instagram.com/rockrevolution',
        websiteLink: 'https://www.rockrevolution.com',
        youtubeLink: 'https://www.youtube.com/rockrevolution',
        eventStart: DateTime.fromISO('02/15/2025, 07:00 PM'),
        eventEnd: DateTime.fromISO('02/15/2025, 09:00 PM'),
        locationId: 17
      },
      {
        title: 'Opera Night',
        subtitle: 'Grand Opera',
        description: 'Experience the grand opera classics',
        facebookLink: 'https://www.facebook.com/operanight',
        instagramLink: 'https://www.instagram.com/operanight',
        websiteLink: 'https://www.operanight.com',
        youtubeLink: 'https://www.youtube.com/operanight',
        eventStart: DateTime.fromISO('02/20/2025, 07:00 PM'),
        eventEnd: DateTime.fromISO('02/20/2025, 09:00 PM'),
        locationId: 21
      },
      {
        title: 'Heavy Metal Thunder',
        subtitle: 'Metal Mayhem',
        description: 'A night of the heaviest metal bands',
        facebookLink: 'https://www.facebook.com/heavymetalthunder',
        instagramLink: 'https://www.instagram.com/heavymetalthunder',
        websiteLink: 'https://www.heavymetalthunder.com',
        youtubeLink: 'https://www.youtube.com/heavymetalthunder',
        eventStart: DateTime.fromISO('02/25/2025, 09:00 PM'),
        eventEnd: DateTime.fromISO('02/25/2025, 11:00 PM'),
        locationId: 23
      },
      {
        title: 'Jazz Night',
        subtitle: 'Smooth Jazz',
        description: 'Relax with the smoothest jazz tunes',
        facebookLink: 'https://www.facebook.com/jazznight',
        instagramLink: 'https://www.instagram.com/jazznight',
        websiteLink: 'https://www.jazznight.com',
        youtubeLink: 'https://www.youtube.com/jazznight',
        eventStart: DateTime.fromISO('03/01/2025, 06:00 PM'),
        eventEnd: DateTime.fromISO('03/01/2025, 08:00 PM'),
        locationId: 16
      }
    ])
  }
}