import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Event from '#models/event'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    await Event.createMany([
      {
        title: 'Jazz Under the Stars: Summer Edition',
        subtitle: 'A Night of Smooth Jazz and Cool Breezes',
        description:
          'Join us for an unforgettable evening of smooth jazz under the summer stars. Enjoy performances by top jazz musicians and immerse yourself in a night of captivating melodies and relaxing vibes.',
        facebookLink: 'https://www.facebook.com/jazzunderthestars',
        instagramLink: 'https://www.instagram.com/jazzunderthestars',
        websiteLink: 'https://www.jazzunderthestars.com',
        youtubeLink: 'https://www.youtube.com/jazzunderthestars',
        eventStart: '2024-07-10T19:00:00',
        eventEnd: '2024-07-10T22:00:00',
        locationId: 5,
      },
      {
        title: 'Summer Beach Festival 2024',
        subtitle: 'Fun in the Sun with Music, Food, and Games',
        description:
          'Experience the ultimate summer beach festival with live music, delicious food, exciting games, and more. Bring your friends and family for a day of fun and sun!',
        facebookLink: 'https://www.facebook.com/summerbeachfestival',
        instagramLink: 'https://www.instagram.com/summerbeachfestival',
        websiteLink: 'https://www.summerbeachfestival.com',
        youtubeLink: 'https://www.youtube.com/summerbeachfestival',
        eventStart: '2024-07-15T10:00:00',
        eventEnd: '2024-07-15T15:00:00',
        locationId: 12,
      },
      {
        title: 'Rock Legends Live',
        subtitle: 'A Tribute to the Greatest Rock Bands',
        description:
          'Get ready to rock out with tributes to the greatest rock bands of all time. This high-energy concert will feature some of the best rock hits from the 70s, 80s, and 90s.',
        facebookLink: 'https://www.facebook.com/rocklegendslive',
        instagramLink: 'https://www.instagram.com/rocklegendslive',
        websiteLink: 'https://www.rocklegendslive.com',
        youtubeLink: 'https://www.youtube.com/rocklegendslive',
        eventStart: '2024-08-05T18:00:00',
        eventEnd: '2024-08-05T21:00:00',
        locationId: 8,
      },
      {
        title: 'Comedy Night at The Laugh Lounge',
        subtitle: 'An Evening of Laughter and Fun',
        description:
          'Join us for a night of non-stop laughter with some of the funniest comedians in the business. The Laugh Lounge is the perfect place to unwind and enjoy a great comedy show.',
        facebookLink: 'https://www.facebook.com/laughlounge',
        instagramLink: 'https://www.instagram.com/laughlounge',
        websiteLink: 'https://www.laughlounge.com',
        youtubeLink: 'https://www.youtube.com/laughlounge',
        eventStart: '2024-07-25T20:00:00',
        eventEnd: '2024-07-25T23:00:00',
        locationId: 3,
      },
      {
        title: 'Art in the Park: Summer Exhibit',
        subtitle: "A Display of Local Artists' Works",
        description:
          'Stroll through the park and enjoy a stunning exhibit of artworks by local artists. From paintings to sculptures, this outdoor event is a celebration of creativity and talent.',
        facebookLink: 'https://www.facebook.com/artinthepark',
        instagramLink: 'https://www.instagram.com/artinthepark',
        websiteLink: 'https://www.artinthepark.com',
        youtubeLink: 'https://www.youtube.com/artinthepark',
        eventStart: '2024-06-30T14:00:00',
        eventEnd: '2024-06-30T18:00:00',
        locationId: 7,
      },
      {
        title: 'Classical Evenings at the Symphony',
        subtitle: 'An Evening of Timeless Classical Music',
        description:
          "Enjoy an enchanting evening of classical music performed by the city's top symphony orchestra. This event promises to be a feast for the ears and a tranquil escape from the everyday hustle and bustle.",
        facebookLink: 'https://www.facebook.com/classicalevenings',
        instagramLink: 'https://www.instagram.com/classicalevenings',
        websiteLink: 'https://www.classicalevenings.com',
        youtubeLink: 'https://www.youtube.com/classicalevenings',
        eventStart: '2024-07-20T19:00:00',
        eventEnd: '2024-07-20T21:30:00',
        locationId: 15,
      },
      {
        title: 'Food Truck Fiesta',
        subtitle: 'A Culinary Adventure with Gourmet Food Trucks',
        description:
          "Satisfy your taste buds at the Food Truck Fiesta, where a variety of gourmet food trucks will be serving up delicious dishes from around the world. It's a culinary adventure you won't want to miss!",
        facebookLink: 'https://www.facebook.com/foodtruckfiesta',
        instagramLink: 'https://www.instagram.com/foodtruckfiesta',
        websiteLink: 'https://www.foodtruckfiesta.com',
        youtubeLink: 'https://www.youtube.com/foodtruckfiesta',
        eventStart: '2024-08-15T11:00:00',
        eventEnd: '2024-08-15T14:00:00',
        locationId: 10,
      },
      {
        title: 'Outdoor Movie Night: Classic Films',
        subtitle: 'Watch Classic Movies Under the Stars',
        description:
          'Bring your blanket and enjoy a night under the stars watching classic movies on the big screen. This outdoor movie night is perfect for film enthusiasts and families alike.',
        facebookLink: 'https://www.facebook.com/outdoormovienight',
        instagramLink: 'https://www.instagram.com/outdoormovienight',
        websiteLink: 'https://www.outdoormovienight.com',
        youtubeLink: 'https://www.youtube.com/outdoormovienight',
        eventStart: '2024-07-05T20:00:00',
        eventEnd: '2024-07-05T23:00:00',
        locationId: 6,
      },
      {
        title: 'Country Music Fest',
        subtitle: 'A Celebration of Country Music',
        description:
          'Join us for the Country Music Fest, featuring live performances by top country music artists. Enjoy a day of great music, food, and fun activities for all ages.',
        facebookLink: 'https://www.facebook.com/countrymusicfest',
        instagramLink: 'https://www.instagram.com/countrymusicfest',
        websiteLink: 'https://www.countrymusicfest.com',
        youtubeLink: 'https://www.youtube.com/countrymusicfest',
        eventStart: '2024-08-01T12:00:00',
        eventEnd: '2024-08-01T17:00:00',
        locationId: 1,
      },
      {
        title: 'Wine and Cheese Tasting',
        subtitle: 'An Evening of Fine Wines and Gourmet Cheeses',
        description:
          'Indulge in an evening of fine wines and gourmet cheeses at our Wine and Cheese Tasting event. Learn about the art of pairing and enjoy a variety of exquisite flavors.',
        facebookLink: 'https://www.facebook.com/wineandcheesetasting',
        instagramLink: 'https://www.instagram.com/wineandcheesetasting',
        websiteLink: 'https://www.wineandcheesetasting.com',
        youtubeLink: 'https://www.youtube.com/wineandcheesetasting',
        eventStart: '2024-07-22T18:00:00',
        eventEnd: '2024-07-22T21:00:00',
        locationId: 2,
      },
      {
        title: 'Reggae Summer Jam',
        subtitle: 'Feel the Rhythm of Reggae',
        description:
          'Come and experience the vibrant rhythms of reggae music at the Reggae Summer Jam. Enjoy live performances by talented reggae bands and dance the night away.',
        facebookLink: 'https://www.facebook.com/reggaesummerjam',
        instagramLink: 'https://www.instagram.com/reggaesummerjam',
        websiteLink: 'https://www.reggaesummerjam.com',
        youtubeLink: 'https://www.youtube.com/reggaesummerjam',
        eventStart: '2024-07-28T16:00:00',
        eventEnd: '2024-07-28T20:00:00',
        locationId: 3,
      },
      {
        title: 'Latin Dance Fiesta',
        subtitle: 'An Evening of Passionate Latin Dance',
        description:
          'Get ready to move your feet at the Latin Dance Fiesta. Experience the energy and passion of Latin dance with live music and dance performances that will keep you dancing all night long.',
        facebookLink: 'https://www.facebook.com/latindancefiesta',
        instagramLink: 'https://www.instagram.com/latindancefiesta',
        websiteLink: 'https://www.latindancefiesta.com',
        youtubeLink: 'https://www.youtube.com/latindancefiesta',
        eventStart: '2024-08-12T18:00:00',
        eventEnd: '2024-08-12T22:00:00',
        locationId: 4,
      },
      {
        title: 'The Great BBQ Cook-Off',
        subtitle: 'A Competition for the Best BBQ in Town',
        description:
          'Do you have what it takes to be the BBQ champion? Join us for The Great BBQ Cook-Off and showcase your grilling skills. Taste delicious BBQ from various competitors and vote for your favorite.',
        facebookLink: 'https://www.facebook.com/bbqcookoff',
        instagramLink: 'https://www.instagram.com/bbqcookoff',
        websiteLink: 'https://www.bbqcookoff.com',
        youtubeLink: 'https://www.youtube.com/bbqcookoff',
        eventStart: '2024-07-18T11:00:00',
        eventEnd: '2024-07-18T14:00:00',
        locationId: 5,
      },
      {
        title: 'Hip Hop Dance Battle',
        subtitle: 'The Ultimate Dance Showdown',
        description:
          "Witness the ultimate dance showdown at the Hip Hop Dance Battle. Dancers from all over will compete in a high-energy battle to see who has the best moves. Don't miss this electrifying event!",
        facebookLink: 'https://www.facebook.com/hiphopdancebattle',
        instagramLink: 'https://www.instagram.com/hiphopdancebattle',
        websiteLink: 'https://www.hiphopdancebattle.com',
        youtubeLink: 'https://www.youtube.com/hiphopdancebattle',
        eventStart: '2024-08-03T17:00:00',
        eventEnd: '2024-08-03T21:00:00',
        locationId: 6,
      },
      {
        title: 'Outdoor Yoga Retreat',
        subtitle: 'A Day of Relaxation and Mindfulness',
        description:
          "Find your inner peace at our Outdoor Yoga Retreat. Spend a day practicing yoga in a serene outdoor setting, led by experienced instructors. It's the perfect way to relax and rejuvenate.",
        facebookLink: 'https://www.facebook.com/outdooryogaretreat',
        instagramLink: 'https://www.instagram.com/outdooryogaretreat',
        websiteLink: 'https://www.outdooryogaretreat.com',
        youtubeLink: 'https://www.youtube.com/outdooryogaretreat',
        eventStart: '2024-06-25T09:00:00',
        eventEnd: '2024-06-25T12:00:00',
        locationId: 7,
      },
      {
        title: 'Indie Film Festival',
        subtitle: 'Showcasing the Best Independent Films',
        description:
          'Celebrate the art of independent filmmaking at the Indie Film Festival. Watch a diverse selection of films from emerging filmmakers and enjoy Q&A sessions with directors and actors.',
        facebookLink: 'https://www.facebook.com/indiefilmfestival',
        instagramLink: 'https://www.instagram.com/indiefilmfestival',
        websiteLink: 'https://www.indiefilmfestival.com',
        youtubeLink: 'https://www.youtube.com/indiefilmfestival',
        eventStart: '2024-08-08T15:00:00',
        eventEnd: '2024-08-08T19:00:00',
        locationId: 8,
      },
      {
        title: 'Tech Innovators Conference',
        subtitle: 'Exploring the Future of Technology',
        description:
          'Join industry leaders and innovators at the Tech Innovators Conference to explore the latest trends and advancements in technology. Network with professionals and learn from expert speakers.',
        facebookLink: 'https://www.facebook.com/techinnovators',
        instagramLink: 'https://www.instagram.com/techinnovators',
        websiteLink: 'https://www.techinnovators.com',
        youtubeLink: 'https://www.youtube.com/techinnovators',
        eventStart: '2024-07-12T09:00:00',
        eventEnd: '2024-07-12T14:00:00',
        locationId: 9,
      },
      {
        title: 'Family Fun Day',
        subtitle: 'A Day of Fun Activities for the Whole Family',
        description:
          "Bring the whole family for a day of fun activities at Family Fun Day. Enjoy games, live entertainment, food stalls, and more. There's something for everyone to enjoy!",
        facebookLink: 'https://www.facebook.com/familyfunday',
        instagramLink: 'https://www.instagram.com/familyfunday',
        websiteLink: 'https://www.familyfunday.com',
        youtubeLink: 'https://www.youtube.com/familyfunday',
        eventStart: '2024-06-28T10:00:00',
        eventEnd: '2024-06-28T14:00:00',
        locationId: 10,
      },
      {
        title: 'Outdoor Adventure Expo',
        subtitle: 'Explore the Great Outdoors',
        description:
          'Discover the latest gear and trends in outdoor adventure at the Outdoor Adventure Expo. Meet experts, attend workshops, and get inspired for your next outdoor adventure.',
        facebookLink: 'https://www.facebook.com/outdoorexpo',
        instagramLink: 'https://www.instagram.com/outdoorexpo',
        websiteLink: 'https://www.outdoorexpo.com',
        youtubeLink: 'https://www.youtube.com/outdoorexpo',
        eventStart: '2024-07-30T11:00:00',
        eventEnd: '2024-07-30T15:00:00',
        locationId: 12,
      },
      {
        title: 'Science Fiction Convention',
        subtitle: 'Celebrating Sci-Fi Culture and Creativity',
        description:
          "Join fellow sci-fi enthusiasts at the Science Fiction Convention. Enjoy panel discussions, cosplay contests, and meet your favorite sci-fi authors and actors. It's a celebration of all things sci-fi!",
        facebookLink: 'https://www.facebook.com/scificonvention',
        instagramLink: 'https://www.instagram.com/scificonvention',
        websiteLink: 'https://www.scificonvention.com',
        youtubeLink: 'https://www.youtube.com/scificonvention',
        eventStart: '2024-08-18T10:00:00',
        eventEnd: '2024-08-18T14:00:00',
        locationId: 13,
      },
      {
        title: 'Culinary Arts Workshop',
        subtitle: 'A Hands-On Cooking Experience',
        description:
          'Learn from top chefs at our Culinary Arts Workshop. This hands-on cooking experience will teach you new techniques and recipes that you can recreate at home. Perfect for food lovers and aspiring chefs.',
        facebookLink: 'https://www.facebook.com/culinaryworkshop',
        instagramLink: 'https://www.instagram.com/culinaryworkshop',
        websiteLink: 'https://www.culinaryworkshop.com',
        youtubeLink: 'https://www.youtube.com/culinaryworkshop',
        eventStart: '2024-07-17T14:00:00',
        eventEnd: '2024-07-17T17:00:00',
        locationId: 15,
      },
      {
        title: 'Mindfulness Meditation Retreat',
        subtitle: 'A Journey to Inner Peace and Calm',
        description:
          'Embark on a journey to inner peace at our Mindfulness Meditation Retreat. Learn meditation techniques, practice mindfulness, and find a sense of calm and relaxation.',
        facebookLink: 'https://www.facebook.com/meditationretreat',
        instagramLink: 'https://www.instagram.com/meditationretreat',
        websiteLink: 'https://www.meditationretreat.com',
        youtubeLink: 'https://www.youtube.com/meditationretreat',
        eventStart: '2024-06-24T09:00:00',
        eventEnd: '2024-06-24T12:00:00',
        locationId: 12,
      },
    ])
  }
}
