import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Address from '#models/address'
// import Hash from '@ioc:Adonis/Core/Hash'

export default class extends BaseSeeder {
  async run() {
    await Address.createMany([
      {
        id: 1,
        name: 'Reflektor',
        street: 'Pl. Xavier-Neujean',
        number: '24',
        zipCode: 4000,
        city: 'Liège',
        country: 'Belgium',
        userId: 3,
        latitude: 50.643309,
        longitude: 5.56793,
      },
      {
        id: 2,
        name: 'Théâtre de Namur',
        street: 'Rue Bruno',
        number: '12',
        zipCode: 5000,
        city: 'Namur',
        country: 'Belgium',
        userId: 3,
        latitude: 50.464848,
        longitude: 4.85732,
      },
      {
        id: 3,
        name: 'Palais des Congrès de Liège',
        street: "Esplanade de l'Europe",
        number: '2',
        zipCode: 4020,
        city: 'Liège',
        country: 'Belgium',
        userId: 3,
        latitude: 50.631248,
        longitude: 5.57452,
      },
      {
        id: 4,
        name: 'Charleroi Expo',
        street: 'Avenue Jean Mermoz',
        number: '50',
        zipCode: 6041,
        city: 'Charleroi',
        country: 'Belgium',
        userId: 3,
        latitude: 50.412742,
        longitude: 4.4477,
      },
      {
        id: 5,
        name: 'Centre culturel de Dinant',
        street: 'Place Reine Astrid',
        number: '3',
        zipCode: 5500,
        city: 'Dinant',
        country: 'Belgium',
        userId: 3,
        latitude: 50.260948,
        longitude: 4.91289,
      },
      {
        id: 6,
        name: 'WEX Wallonie Expo',
        street: 'Rue des Deux Provinces',
        number: '1',
        zipCode: 6900,
        city: 'Marche-en-Famenne',
        country: 'Belgium',
        userId: 3,
        latitude: 50.2527,
        longitude: 5.26859,
      },
      {
        id: 7,
        name: 'Maison de la Culture de Tournai',
        street: 'Rue des Carmes',
        number: '3',
        zipCode: 7500,
        city: 'Tournai',
        country: 'Belgium',
        userId: 3,
        latitude: 50.607755,
        longitude: 3.38258,
      },
      {
        id: 8,
        name: 'Aula Magna',
        street: 'Place Raymond Lemaire',
        number: '1',
        zipCode: 1348,
        city: 'Louvain-la-Neuve',
        country: 'Belgium',
        userId: 3,
        latitude: 50.66829,
        longitude: 4.61443,
      },
      {
        id: 9,
        name: 'Centre Culturel de Huy',
        street: 'Rue Saint-Germain',
        number: '126',
        zipCode: 4500,
        city: 'Huy',
        country: 'Belgium',
        userId: 3,
        latitude: 50.527026,
        longitude: 5.23307,
      },
      {
        id: 10,
        name: 'Centre Culturel de Seraing',
        street: 'Rue Renaud Strivay',
        number: '44',
        zipCode: 4100,
        city: 'Seraing',
        country: 'Belgium',
        userId: 3,
        latitude: 50.58362,
        longitude: 5.50115,
      },
      {
        id: 11,
        name: 'Centre Culturel de Rochefort',
        street: 'Rue de Behogne',
        number: '6',
        zipCode: 5580,
        city: 'Rochefort',
        country: 'Belgium',
        userId: 3,
        latitude: 50.159261,
        longitude: 5.22326,
      },
      {
        id: 12,
        name: 'Centre Culturel de Spa',
        street: 'Place Royale',
        number: '2',
        zipCode: 4900,
        city: 'Spa',
        country: 'Belgium',
        userId: 3,
        latitude: 50.491922,
        longitude: 5.86434,
      },
      {
        id: 13,
        name: 'Cinéma Churchill',
        street: 'Place Emile Vandervelde',
        number: '3',
        zipCode: 1348,
        city: 'Louvain-la-Neuve',
        country: 'Belgium',
        userId: 3,
        latitude: 50.66829,
        longitude: 4.61443,
      },
      {
        id: 14,
        name: 'Maison de la Culture Famenne-Ardenne',
        street: 'Place Roi Baudouin',
        number: '1',
        zipCode: 6900,
        city: 'Marche-en-Famenne',
        country: 'Belgium',
        userId: 3,
        latitude: 50.2527,
        longitude: 5.26859,
      },
      {
        id: 15,
        name: 'La Spirale',
        street: 'Rue de Mulhouse',
        number: '36',
        zipCode: 4000,
        city: 'Liège',
        country: 'Belgium',
        userId: 3,
        latitude: 50.633231,
        longitude: 5.58557,
      },
    ])
  }
}
